<?php
$GLOBALS['title'] = "NewHydrogen | BioSolar Announces $5.0 Million Private Placement Offering";
$GLOBALS['desc'] = "";
$GLOBALS['keywords'] = "";
include('header.php'); ?>


<div class="subpages_frame text-center">
    <div class="container">
        <h1>BioSolar Announces $5.0 Million Private Placement Offering</h1>
    </div>
</div>
<div class="inner_page single_pagee">
    <div class="container">

        <p><strong>Company is exploring other major cost reduction opportunities in hydrogen electrolyzers beyond the scope of its current research project at UCLA</strong></p>

        <p>SANTA CLARITA, Calif., Jan. 19, 2021 (GLOBE NEWSWIRE) -- BioSolar, Inc. (OTC:BSRC) (“BioSolar” or the “Company”), a developer of clean energy technologies, today announced that its wholly owned subsidiary NewHydrogen, Inc. is exploring additional major cost reduction opportunities in hydrogen electrolyzers beyond the scope of its current sponsored research project at the University of California Los Angeles (“UCLA”).<br></p>
        <p>A mature technology that has existed for over 200 years, electrolyzers are systems typically installed behind a solar farm or wind farm that use renewable electricity to split water into hydrogen and oxygen, thereby producing Green Hydrogen. The main challenge and reason that humans do not utilize Green Hydrogen everywhere today is their high cost. The catalysts that enable the critical water-splitting reactions are currently made from platinum and iridium, two very expensive precious metals that account for nearly 50% of the cost of the electrolyzer.</p>
        <p>The current sponsored research program at UCLA is focused on replacing iridium, a precious metal found only in asteroids, with earth abundant materials that meet or exceed the performance characteristics of iridium. The Company has also identified additional components and materials in electrolyzers where meaningful cost reductions can be performed. While iridium is the oxygen catalyst, its counterpart on the hydrogen side is platinum, a material so rare that only 200 tons are mined every year. Another critical component is the porous transport layer (“PTL”), aka gas diffusion layer, which facilitates the movement of water and gases to and from the catalyst surfaces. According to the National Renewable Energy Laboratory, the catalysts, membrane and PTL assembly account for more than 50%-75% of the capital cost of the electrolyzer stack.</p>
        <p>“We selected UCLA because they are one of the top research institutions in the country with a deep pool of talented researchers and state of the art facilities, and because they already have a high-performance catalyst candidate from a different program that positions us well for growth,” said Dr. David Lee, CEO of BioSolar. “The UCLA team has extensive experience in nanoscale materials and nanotechnology to impact a wide range of technologies including materials synthesis, catalysis, fuel cells, biomedical and devices applications. With a strong research foundation in place, we are excited for what comes next.”</p>
        <p>Dr. Lee continued, “We intend to aggressively expand our research programs to reduce the cost of these major material components to significantly reduce the cost of green hydrogen production. Whether doing more at UCLA, or building out our in-house team, partnering with other top research institutions, we are fully committed to a future powered by Green Hydrogen. Goldman Sachs calls Green Hydrogen a ‘once in a lifetime’ <a href="https://www.globenewswire.com/Tracker?data=LKNRjGKU024DTP-iWBfg1WuA5qu2qmUU33n6UebX0AlyuThuLVZb10pRzGz6QbnV5RPvOpe7aJnXC2dzcNKbL7_3Bxag7cL_c0LZoP1yCO5kdik5fL3FbZyrjVMZyMFUp_WiRZZIYNeJDEbcWiDFfxOaIs_2JxlCYCVnKo-FQIz5sxMClTMFswkUq-uCYFF_AjzYf9uquEk17kDCzmrNPVg2_C1J6B3kI8fdOdZC0aGXUzwAcfB1e_TzSCZqbT1b4Pp3yflvuil9YwxcUFjF_w==" rel="nofollow" target="_blank" title="$12 trillion market opportunity">$12 trillion market opportunity</a>. We are excited to be a part of this revolution to establish a more sustainable future.”</p>
        <p><strong>About BioSolar, Inc.</strong></p>
        <p>BioSolar is developing breakthrough technologies to increase the storage capacity, lower the cost and extend the life of lithium-ion batteries for electric vehicles. The need for such breakthroughs is critical to meet the expected demand of the rapidly growing global electric vehicle battery market, which is forecast to exceed $90 billion by 2025. A lithium-ion battery contains two major parts, a lithium-filled cathode and a lithium-receiving anode, that function together as the positive and negative sides of the battery. BioSolar is developing innovative technologies that will enable the use of inexpensive silicon as the anode material to create next generation high energy and high-power lithium-ion batteries for electric vehicles. Founded with the vision of developing breakthrough energy technologies, BioSolar's previous successes include the world's first bio-based backsheet for use in solar panels. To learn more about BioSolar, please visit our website at&nbsp;<a href="https://www.globenewswire.com/Tracker?data=KIs3KnXLyW8uwjdL5H-93euRWqY5HRSJZnC9yHZOBypl3fdsnFlsl1HDmTKb7uGdlCS7_IDp0KqCwD3Lkn3BxoI2O1mmcCGjVJ3TPGypVCU=" rel="nofollow" target="_blank" title="">https://www.biosolar.com</a>.</p>
        <p><strong>About NewHydrogen, Inc.</strong></p>
        <p>NewHydrogen, Inc., a wholly owned subsidiary of BioSolar, Inc., is focused on developing a breakthrough electrolyzer technology to lower the cost of green hydrogen. Hydrogen is the cleanest and most abundant fuel in the universe. It is zero-emission and only produces water vapor when used. However, hydrogen does not exist in its pure form on Earth so it must be extracted. For centuries, scientists have known how to split water into hydrogen and oxygen using a simple and elegant device called an electrolyzer. Unfortunately, electrolyzers are expensive and rely on rare earth materials such as platinum and iridium – literally stardust found only in asteroids. These materials account for nearly 50% of the cost of electrolyzers. NewHydrogen is developing a breakthrough electrolyzer technology to replace rare earth materials with inexpensive earth abundant materials to help usher in a green hydrogen economy that Goldman Sacks estimated to be worth $12 trillion by 2050. To learn more about NewHydrogen.</p>
        <p><strong>Safe Harbor Statement</strong><br>Matters discussed in this press release contain forward-looking statements within the meaning of the Private Securities Litigation Reform Act of 1995. When used in this press release, the words "anticipate," "believe," "estimate," "may," "intend," "expect" and similar expressions identify such forward-looking statements. Actual results, performance or achievements could differ materially from those contemplated, expressed or implied by the forward-looking statements contained herein. These forward-looking statements are based largely on the expectations of the Company and are subject to a number of risks and uncertainties. These include, but are not limited to, risks and uncertainties associated with: the impact of economic, competitive and other factors affecting the Company and its operations, markets, product, and distributor performance, the impact on the national and local economies resulting from terrorist actions, and U.S. actions subsequently; and other factors detailed in reports filed by the Company with the United Stated Securities and Exchange Commission.</p>
        <p>Any forward-looking statement made by us in this press release is based only on information currently available to us and speaks only as of the date on which it is made. We undertake no obligation to publicly update any forward-looking statement, whether written or oral, that may be made from time to time, whether as a result of new information, future developments or otherwise.</p>



        <p><strong>Investor Relations Contact:</strong></p>
        <p>Tom Becker <br>
            NewHydrogen, Inc.</p>
        <a href="mailto:ir@newhydrogen.com">ir@newhydrogen.com</a> <br>
        <a href="tel:8779043733">(877) 904-3733</a>
    </div>
</div>


<?php include('footer.php'); ?>